In [3]:
from statsmodels.stats import inter_rater as irr
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.metrics import balanced_accuracy_score, matthews_corrcoef, cohen_kappa_score, roc_auc_score, log_loss

In [4]:
df = pd.read_csv('df_final.csv')
df.head()

   Unnamed: 0  ...     majority
0           0  ...   ['Jewish']
1           1  ...    ['Other']
2           2  ...  ['African']
3           3  ...     ['Arab']
4           4  ...           []

[5 rows x 31 columns]

In [5]:
# Trying to answer: How accurate are humans? What is the inter-rater agreement of different raters?
# Making list of lists to observe differing ratings
ann1_rating = df['annotator_1_targets']
ann2_rating = df['annotator_2_targets']
ann3_rating = df['annotator_3_targets']
data = {'rater1': ann1_rating, 'rater2': ann2_rating, 'rater3': ann3_rating}

raters = pd.DataFrame(data)
raters

                                  rater1  ...                          rater3
0                             ['Jewish']  ...                      ['Jewish']
1                       ['Men', 'Other']  ...                       ['Women']
2                            ['African']  ...                        ['None']
3                              ['Asian']  ...                        ['Arab']
4                          ['Caucasian']  ...                    ['Economic']
...                                  ...  ...                             ...
19224                          ['Islam']  ...                        ['None']
19225                       ['Hispanic']  ...                       ['Asian']
19226                          ['Islam']  ...                       ['Islam']
19227  ['Minority', 'Refugee', 'Indian']  ...            ['Refugee', 'Islam']
19228               ['African', 'Islam']  ...  ['African', 'Islam', 'Jewish']

[19229 rows x 3 columns]

In [ ]:
# Calculating Fleiss' kappa over Cohen's kappa due to ability to compare >2 raters
# Fleiss' kappa uses a single pooled marginal (Pij), treating all raters as if they draw from the same distribution. 
# Averages away noise
# First, converting data to format accepted by Fleiss' kappa
table, categories = irr.aggregate_raters(raters)

# Now calculating the kappa
f_kappa = irr.fleiss_kappa(table, method = 'fleiss')
rand_kappa = irr.fleiss_kappa(table, method = 'rand')

print(f_kappa, rand_kappa)

0.46425474930691374 0.5469024941339379